added social media icons
fluid-project/fluidproject.org pull request #46
Opened 2020-03-21 04:18 UTC by AbdullahiAbdulkabir

Added social icons as said in #30 

![image](https://user-images.githubusercontent.com/33360580/77219157-426a7a80-6b33-11ea-99e4-1be9a52f4bcb.png)

2020-03-23 12:57 UTC, sachin10101998 commented on src/partials/styles.html.eco
> +<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
Do we really need to add a new library to solve this issue? Bootstrap has an MIT license and the Fluid project has a Creative Commons Attribution License which may lead to conflicts. We should discuss the need of addition of a library and it should be added only if it's absolutely necessary.

2020-03-23 16:02 UTC, AbdullahiAbdulkabir commented on src/partials/styles.html.eco
> +<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
Fine, I will fix that.

2020-09-05 08:11 UTC, Raunaksingh100 requested changes
The issue #30   already closed , so no need of this

2020-09-05 16:42 UTC, closed without merging

2020-09-05 16:42 UTC, AbdullahiAbdulkabir commented
Closed in favour of the admin.