feat: update project structure to follow changes in Trivet
fluid-project/fluidproject.org pull request #96
Opened 2023-08-17 15:17 UTC by chosww

- move output to _site
- update workflows
- add Dependabot configuration
- update markdown config
- add sitemap
- add robots
- update lintings

2023-08-17 16:32 UTC, greatislander requested changes

2023-08-17 16:32 UTC, greatislander commented on src/_locales/messages.js
> +// WARNING! This file is generated by a tool.
I don't think this project has any localized content, so this file and its directory shouldn't be needed.

2023-08-17 16:32 UTC, greatislander commented on eleventy.config.js
> +        css: {
As this site isn't localized, you should add `i18n: false` to the configuration object here.

2023-08-17 16:32 UTC, greatislander commented on src/_transforms/parse-transform.js
> +const minify = require("../_utils/minify.js");
Remove this and instead use the same package used in the `minify` transform in `eleventy-plugin-fluid` as it's already a dependency.

2023-08-17 16:33 UTC, greatislander requested changes
This also needs an RSS feed for news, see #93.

2023-08-17 19:05 UTC, chosww commented on src/sitemap.njk
> +    {% set pages = ["index.html", "404.html", "about.html", "infusion.html", "news/index.html", "projects.html"] %}
Oh, I didn't know eleventy recognizes htmls outside of collections directory. Thanks for asking, using collections.all works great 👍

2023-08-18 12:04 UTC, greatislander requested changes
The 404 file is showing up on the sitemap. To prevent it from showing up there, you need to make sure it is excluded from collections.

2023-08-18 12:06 UTC, greatislander requested changes

2023-08-18 12:06 UTC, greatislander commented on .github/workflows/release-please.yml
> +          package-name: floeproject.org
The package name needs to match the project

2023-08-18 12:08 UTC, greatislander commented on .gitignore
>  package-lock.json
The `package-lock.json` file should not be ignore.

2023-08-18 13:55 UTC, greatislander approved these changes

2023-08-18 13:55 UTC, merged